/**
 * ╔══════════════════════════════════════════════════════════════╗
 * ║         SOLESENSE — ESP32-S3 Firmware  (Task 3)             ║
 * ║         Sensor acquisition only — no Wi-Fi yet              ║
 * ╠══════════════════════════════════════════════════════════════╣
 * ║  Sensors   : 4× FSR  ·  TMP117  ·  MPU6050                 ║
 * ║  Rate      : 20 Hz                                          ║
 * ║  Output    : Serial  (115200 baud)                          ║
 * ║  Platform  : ESP32-S3 (Arduino framework)                   ║
 * ╠══════════════════════════════════════════════════════════════╣
 * ║  ⚠  NOT a medical device.  Research prototype only.         ║
 * ╚══════════════════════════════════════════════════════════════╝
 *
 * ── Required Arduino libraries ──────────────────────────────────────────────
 *  Install each via  Tools → Manage Libraries  in Arduino IDE:
 *
 *  1. "Adafruit MPU6050"                   by Adafruit
 *     (also installs Adafruit BusIO and Adafruit Unified Sensor automatically)
 *
 *  2. "SparkFun TMP117 Arduino Library"    by SparkFun Electronics
 *
 * ── Board setup ─────────────────────────────────────────────────────────────
 *  1. File → Preferences → Additional boards URL:
 *       https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
 *  2. Tools → Board Manager → search "esp32" → install by Espressif ≥ 2.0.14
 *  3. Tools → Board → ESP32 Arduino → "ESP32S3 Dev Module"
 *  4. Tools → Port → select your COM port
 *  5. Click Upload
 *
 * ── Serial commands ──────────────────────────────────────────────────────────
 *  Open Serial Monitor at 115200 baud, line ending = Newline
 *
 *  D  → print full sensor diagnostic (single snapshot)
 *  C  → enter FSR calibration mode (hold insole unloaded before pressing)
 *  E  → erase saved calibration from flash
 *  H  → print this help text
 *
 * ── Startup modes ───────────────────────────────────────────────────────────
 *  Normal boot         → sensor loop + serial output at 20 Hz
 *  Hold BOOT (GPIO 0)  → enters FSR calibration mode immediately
 *
 * ── Pin configuration ────────────────────────────────────────────────────────
 *  All pins are set in config.h.  Do not edit this file for pin changes.
 *
 *  Default (ESP32-S3-DevKitC-1):
 *    FSR1  GPIO 1   ADC1_CH0
 *    FSR2  GPIO 2   ADC1_CH1
 *    FSR3  GPIO 3   ADC1_CH2
 *    FSR4  GPIO 4   ADC1_CH3
 *    SDA   GPIO 8
 *    SCL   GPIO 9
 *
 *  ⚠ Use only ADC1 pins for FSRs (GPIO 1–10).
 *    ADC2 (GPIO 11–20) conflicts with Wi-Fi and gives unreliable readings.
 */

#include "config.h"
#include "calibration.h"
#include "sensors.h"
#include "wifi_tx.h"
#include <Arduino.h>

// ─────────────────────────────────────────────────────────────────────────────
//  BOOT button  (GPIO 0 on all standard ESP32-S3 devkits)
// ─────────────────────────────────────────────────────────────────────────────
#define BOOT_BUTTON_PIN  0

// ─────────────────────────────────────────────────────────────────────────────
//  State
// ─────────────────────────────────────────────────────────────────────────────
static uint32_t _last_sample_ms  = 0;
static uint32_t _sample_count    = 0;

// ─────────────────────────────────────────────────────────────────────────────
//  Forward declarations
// ─────────────────────────────────────────────────────────────────────────────
static void print_help();
static void print_sensor_line(const SensorPacket &pkt);

// ═════════════════════════════════════════════════════════════════════════════
//  setup()
// ═════════════════════════════════════════════════════════════════════════════
void setup() {

    Serial.begin(SERIAL_BAUD);
    delay(600);   // allow Serial Monitor to attach before first print

    // ── Banner ────────────────────────────────────────────────────────────────
    Serial.println();
    Serial.println(F("╔══════════════════════════════════════════════╗"));
    Serial.println(F("║      SOLESENSE  ESP32-S3  SENSOR FIRMWARE    ║"));
    Serial.println(F("║      Tasks 3-5 — Sensors + Wi-Fi TX          ║"));
    Serial.println(F("╚══════════════════════════════════════════════╝"));
    Serial.println();

    // ── ADC configuration ────────────────────────────────────────────────────
    // 12-bit resolution → values 0–4095
    analogReadResolution(ADC_RESOLUTION_BITS);

    // ADC_11db attenuation = full 0–3.3 V input range.
    // Lower attenuation gives better resolution at low voltages, but FSR
    // voltage dividers can swing to 3.3 V under heavy load, so 11 dB is safer.
    analogSetAttenuation(ADC_11db);

    Serial.printf("ADC: %d-bit resolution, 11dB attenuation (0–3.3V range)\n",
                  ADC_RESOLUTION_BITS);

    // ── BOOT button ──────────────────────────────────────────────────────────
    pinMode(BOOT_BUTTON_PIN, INPUT_PULLUP);

    // ── Calibration ──────────────────────────────────────────────────────────
    // Load saved FSR baselines from NVS flash.
    // Must happen BEFORE sensors_init() so the baselines are available for
    // the first sensors_read() call.
    calibration_load();
    calibration_status();   // one-line status line after loading

    // If BOOT button is held at power-on → run calibration immediately.
    // This avoids the need to send a serial command.
    if (digitalRead(BOOT_BUTTON_PIN) == LOW) {
        Serial.println(F("[BOOT] BOOT button held → entering FSR calibration"));
        calibration_run();
    }

    // ── Sensor init ──────────────────────────────────────────────────────────
    Serial.println(F("[INIT] Initialising sensors..."));
    bool all_ok = sensors_init();

    Serial.println();
    if (all_ok) {
        Serial.println(F("[INIT] All sensors OK."));
    } else {
        Serial.println(F("[INIT] WARNING: one or more sensors not detected."));
        Serial.println(F("       Check wiring, power, and I2C addresses in config.h."));
        Serial.println(F("       Firmware will continue with available sensors."));
    }

    // ── Startup diagnostic ────────────────────────────────────────────────────
    Serial.println(F("[INIT] Running startup diagnostic..."));
    sensors_diagnostic();

    // ── Pin summary ───────────────────────────────────────────────────────────
    Serial.println(F("Pin assignment:"));
    Serial.printf( "  FSR1 → GPIO %d  (forefoot medial)\n",  FSR1_PIN);
    Serial.printf( "  FSR2 → GPIO %d  (forefoot lateral)\n", FSR2_PIN);
    Serial.printf( "  FSR3 → GPIO %d  (midfoot)\n",          FSR3_PIN);
    Serial.printf( "  FSR4 → GPIO %d  (heel)\n",             FSR4_PIN);
    Serial.printf( "  SDA  → GPIO %d\n",                     I2C_SDA);
    Serial.printf( "  SCL  → GPIO %d\n",                     I2C_SCL);
    Serial.printf( "  TMP117  @ I2C 0x%02X  — %s\n",
                   TMP117_I2C_ADDR,
                   sensors_tmp117_ok() ? "FOUND" : "NOT FOUND");
    Serial.printf( "  MPU6050 @ I2C 0x%02X  — %s\n",
                   MPU6050_I2C_ADDR,
                   sensors_mpu6050_ok() ? "FOUND" : "NOT FOUND");
    Serial.println();

    print_help();

    // ── Wi-Fi ─────────────────────────────────────────────────────────────────
    // wifi_connect() blocks up to WIFI_CONNECT_TIMEOUT_MS then returns.
    // If it times out, the sensor loop starts anyway; wifi_maintain() in
    // loop() keeps retrying in the background without blocking anything.
    wifi_connect();

    Serial.printf("[LOOP] Starting sensor loop at %d Hz  (%d ms interval)\n",
                  SAMPLE_RATE_HZ, SAMPLE_INTERVAL_MS);
    Serial.println(F("       Serial output: once per second"));
    Serial.println(F("       Wi-Fi TX: every packet (~20 Hz)"));
    Serial.println(F("       Send 'D' for full diagnostic at any time."));
    Serial.println();

    _last_sample_ms = millis();
}

// ═════════════════════════════════════════════════════════════════════════════
//  loop()
// ═════════════════════════════════════════════════════════════════════════════
void loop() {

    // ── Serial command handler ────────────────────────────────────────────────
    if (Serial.available()) {
        char cmd = (char) toupper(Serial.read());

        // Flush rest of line
        while (Serial.available()) Serial.read();

        switch (cmd) {
            case 'D':
                Serial.println(F("[CMD] Diagnostic requested..."));
                calibration_status();
                sensors_diagnostic();
                calibration_print();
                break;

            case 'C':
                Serial.println(F("[CMD] Calibration mode..."));
                calibration_run();
                break;

            case 'E':
                Serial.println(F("[CMD] Erasing calibration..."));
                calibration_erase();
                break;

            case 'W':
                Serial.println(F("[CMD] Wi-Fi status..."));
                wifi_print_status();
                break;

            case 'H':
                print_help();
                break;

            default:
                Serial.printf("[CMD] Unknown command '%c' — send H for help\n", cmd);
                break;
        }
    }

    // ── Wi-Fi watchdog (non-blocking) ────────────────────────────────────────
    // Must be called every loop iteration.  Handles reconnect timing without
    // blocking the sensor sample gate below.
    wifi_maintain();

    // ── Timing gate: fire at SAMPLE_INTERVAL_MS ───────────────────────────────
    uint32_t now = millis();
    if (now - _last_sample_ms < (uint32_t)SAMPLE_INTERVAL_MS) {
        return;
    }
    _last_sample_ms = now;
    _sample_count++;

    // ── Read all sensors ──────────────────────────────────────────────────────
    SensorPacket pkt;
    sensors_read(pkt);

    // ── Transmit over Wi-Fi ───────────────────────────────────────────────────
    // Send every packet.  wifi_send_packet() returns immediately (false)
    // if Wi-Fi is not connected, so sensor acquisition is never blocked.
    wifi_send_packet(pkt);

    // ── Serial output every 20 samples (~1 s) ────────────────────────────────
    // Print all values in the exact format required by Task 3.
    // Printing every sample (50 ms) would flood the terminal; once per second
    // is readable while still showing live changes.
    if (_sample_count % (uint32_t)SAMPLE_RATE_HZ == 0) {
        print_sensor_line(pkt);
    }
}

// ═════════════════════════════════════════════════════════════════════════════
//  print_sensor_line()
//  Exact format specified in Task 3 — one block per second
// ═════════════════════════════════════════════════════════════════════════════
static void print_sensor_line(const SensorPacket &pkt) {

    Serial.println(F("─────────────────────────────────────────"));

    // FSR — calibrated (baseline-subtracted) values
    Serial.printf("FSR1: %d\n", pkt.fsr.calibrated[0]);
    Serial.printf("FSR2: %d\n", pkt.fsr.calibrated[1]);
    Serial.printf("FSR3: %d\n", pkt.fsr.calibrated[2]);
    Serial.printf("FSR4: %d\n", pkt.fsr.calibrated[3]);

    // Temperature
    if (pkt.tmp117.ok) {
        Serial.printf("TEMP: %.2f C\n", pkt.tmp117.temperature_c);
    } else {
        Serial.println(F("TEMP: NOT FOUND"));
    }

    // IMU
    if (pkt.mpu.ok) {
        Serial.printf("AX: %.4f\n", pkt.mpu.ax);
        Serial.printf("AY: %.4f\n", pkt.mpu.ay);
        Serial.printf("AZ: %.4f\n", pkt.mpu.az);
        Serial.printf("GX: %.4f\n", pkt.mpu.gx);
        Serial.printf("GY: %.4f\n", pkt.mpu.gy);
        Serial.printf("GZ: %.4f\n", pkt.mpu.gz);
    } else {
        Serial.println(F("AX: NOT FOUND"));
        Serial.println(F("AY: NOT FOUND"));
        Serial.println(F("AZ: NOT FOUND"));
        Serial.println(F("GX: NOT FOUND"));
        Serial.println(F("GY: NOT FOUND"));
        Serial.println(F("GZ: NOT FOUND"));
    }

    // Timestamp and Wi-Fi status
    Serial.printf("T:   %lu ms  |  WiFi: %s\n",
                  pkt.timestamp_ms,
                  wifi_is_connected() ? "OK" : "DISCONNECTED");
}

// ═════════════════════════════════════════════════════════════════════════════
//  print_help()
// ═════════════════════════════════════════════════════════════════════════════
static void print_help() {
    Serial.println(F("Serial commands (115200 baud, send single letter + Enter):"));
    Serial.println(F("  D  — sensor diagnostic snapshot"));
    Serial.println(F("  C  — FSR calibration mode (remove all weight first)"));
    Serial.println(F("  E  — erase saved FSR calibration from flash"));
    Serial.println(F("  W  — Wi-Fi status and TX counters"));
    Serial.println(F("  H  — this help text"));
    Serial.println();
}
