/**
 * SoleSense ESP32-S3 Firmware
 * wifi_tx.h  —  Wi-Fi connection and HTTP POST transmission API
 *
 * ─── Responsibility ──────────────────────────────────────────────────────────
 *
 *  This module handles everything between the sensor loop and the laptop:
 *    1. Connecting to the configured Wi-Fi network
 *    2. Staying connected (non-blocking reconnect watchdog)
 *    3. Serialising a SensorPacket to a flat JSON string
 *    4. HTTP POSTing that string to the laptop receiver
 *    5. Reporting connection state over Serial
 *
 *  Sensor acquisition continues uninterrupted if Wi-Fi is unavailable.
 *  Packets are simply not sent during disconnections; no buffering.
 *
 * ─── Configuration ───────────────────────────────────────────────────────────
 *
 *  All settings are in config.h — do not edit this file:
 *
 *    AP_SSID      hotspot name the laptop will see  (default "SoleSense")
 *    AP_PASSWORD  hotspot password  (default "solesense123")
 *    AP_CHANNEL   Wi-Fi channel 1–13  (default 1)
 *    SERVER_IP    laptop IP after joining the hotspot  (default 192.168.4.2)
 *    SERVER_PORT  receiver port  (default 5005)
 *    SERVER_ENDPOINT  HTTP path  (default /api/sensor)
 *
 * ─── JSON schema sent to laptop ──────────────────────────────────────────────
 *
 *  Flat format — all fields at the top level (no nesting):
 *
 *  {
 *    "timestamp": 123456789,    ESP32 millis() in ms
 *    "fsr1":      421,          calibrated ADC count — forefoot medial
 *    "fsr2":      380,          calibrated ADC count — forefoot lateral
 *    "fsr3":      210,          calibrated ADC count — midfoot
 *    "fsr4":      510,          calibrated ADC count — heel
 *    "temperature": 31.42,      °C from TMP117  (omitted if sensor absent)
 *    "ax":  0.0312,             acceleration x, g
 *    "ay": -0.0198,             acceleration y, g
 *    "az":  0.9871,             acceleration z, g
 *    "gx":  1.2400,             angular velocity x, °/s
 *    "gy": -0.8100,             angular velocity y, °/s
 *    "gz":  0.3200              angular velocity z, °/s
 *  }
 *
 *  If TMP117 is unavailable, "temperature" is omitted from the object
 *  (the Python receiver treats missing key as null).
 *  If MPU6050 is unavailable, ax..gz are all 0.0.
 *
 *  This flat layout matches src/hardware_input.parse_flat_packet() exactly.
 *
 * ─── Required libraries ──────────────────────────────────────────────────────
 *
 *  WiFi.h        —  built into ESP32 Arduino core (no install needed)
 *  HTTPClient.h  —  built into ESP32 Arduino core (no install needed)
 *  ArduinoJson   —  install via Arduino Library Manager (Benoit Blanchon ≥ 6.x)
 */

#pragma once
#include "sensors.h"   // SensorPacket

// ─────────────────────────────────────────────────────────────────────────────
//  API
// ─────────────────────────────────────────────────────────────────────────────

/**
 * wifi_connect()
 *
 * Attempt to join the network configured in config.h (WIFI_SSID / WIFI_PASSWORD).
 * Blocks until connected or WIFI_CONNECT_TIMEOUT_MS elapses.
 *
 * Returns true  on success.
 * Returns false on timeout — the sensor loop continues regardless; wifi_maintain()
 * will keep retrying in the background.
 *
 * Call once from setup().
 */
bool wifi_connect();

/**
 * wifi_is_connected()
 *
 * Lightweight connection check.  Returns true if Wi-Fi is currently associated.
 * Does NOT trigger a reconnect — call wifi_maintain() for that.
 */
bool wifi_is_connected();

/**
 * wifi_maintain()
 *
 * Non-blocking connection watchdog.  Call every loop() iteration.
 *
 * Behaviour:
 *   - If connected  : returns immediately (no work done)
 *   - If just dropped: logs the disconnect to Serial once
 *   - If disconnected for > WIFI_RECONNECT_INTERVAL_MS: attempts WiFi.begin()
 *
 * Never blocks the sensor loop.
 */
void wifi_maintain();

/**
 * wifi_send_packet()
 *
 * Serialise pkt to flat JSON and HTTP POST to SERVER_IP:SERVER_PORT/SERVER_ENDPOINT.
 *
 * Returns true  if the server responded HTTP 200.
 * Returns false if:
 *   - Wi-Fi is not connected (no-op, no error printed)
 *   - HTTP request timed out (HTTP_TIMEOUT_MS)
 *   - Server returned a non-200 status code
 *
 * On failure in DEBUG_MODE, the HTTP status code is printed to Serial.
 * The sensor loop always continues regardless of return value.
 */
bool wifi_send_packet(const SensorPacket &pkt);

/**
 * wifi_print_status()
 *
 * Print a multi-line Wi-Fi status block to Serial:
 *
 *   [WiFi] Status : CONNECTED
 *   [WiFi] SSID   : MyNetwork
 *   [WiFi] IP     : 192.168.1.42
 *   [WiFi] RSSI   : -54 dBm
 *   [WiFi] Target : http://192.168.1.100:5005/api/sensor
 *
 * Safe to call at any time.
 */
void wifi_print_status();
